# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2ae41abb323e7d6c3ebb8d7656263b49ffb638419b7b5f829096dfc48e95fa1cff4cd17da22c2ebc2098397e9390b45e38ee70eb9a60e34f9ee96a28f295c6

test:
  secret_key_base: 48e56f7a3d58df7b3894678f0ee7dd87280004ae0220f56570eaf4aaf09a22cdd3bc69e47f740e71c45ab882e915df086998167b6a6c46c4220a6d8de7a5cca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
